# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 700)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.combo_type = QtWidgets.QComboBox(Form)
        self.combo_type.setObjectName("combo_type")
        self.combo_type.addItem("")
        self.combo_type.addItem("")
        self.horizontalLayout.addWidget(self.combo_type)
        self.btn_search = QtWidgets.QPushButton(Form)
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout.addWidget(self.btn_search)
        self.btn_refresh = QtWidgets.QPushButton(Form)
        self.btn_refresh.setObjectName("btn_refresh")
        self.horizontalLayout.addWidget(self.btn_refresh)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.table_records = QtWidgets.QTableWidget(Form)
        self.table_records.setObjectName("table_records")
        self.table_records.setColumnCount(0)
        self.table_records.setRowCount(0)
        self.gridLayout.addWidget(self.table_records, 1, 0, 1, 1)
        self.label_image = QtWidgets.QLabel(Form)
        self.label_image.setFrameShape(QtWidgets.QFrame.Box)
        self.label_image.setAlignment(QtCore.Qt.AlignCenter)
        self.label_image.setObjectName("label_image")
        self.gridLayout.addWidget(self.label_image, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "智慧工地 - 数据管理中心"))
        self.combo_type.setItemText(0, _translate("Form", "全部记录"))
        self.combo_type.setItemText(1, _translate("Form", "未戴安全帽"))
        self.btn_search.setText(_translate("Form", "🔍 分类查询"))
        self.btn_refresh.setText(_translate("Form", "🔄 刷新全部数据"))
        self.label_image.setText(_translate("Form", "点击左侧表格查看抓拍回放"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
